[colors]
SECONDARY_BUTTON = "#7A999E"
CANCEL_QUIT = "#A4CDCA"
HIGHLIGHT = "#F0F6F9"
TABLE_HEADER = "#7A999E"
PRIMARY_BUTTON = "#212F3E"
PRIMARY_INTENSE = "#293241"
LOW_CONTRAST = "#EBEBEB"
LOW_CONTRAST2 = "#91969D"
OUTLINE = "#767C85"
SCORLL_BAR = "#F0F6F9"
GREYDARK = "#545B67"
BORDER = "#484847"
GREYEXTRALIGHT = "#F0F6F9"
MAIN_TEXT = "#000000"
MAIN_BACKGROUND = "#FFFFFF"
SUB_BACKGROUND = "#F0F6F9"
WHITE = "#FFFFFF"
TABLE_BORDER = "#484847"
INPUT_TEXT = "#000000"
INPUT_BORDER = "#000000"
INPUT_BACKGROUND = "#FFFFFF"

[styleSheet]
basic = "background-color: #fff; color: #000"
goToMain = "border:none; color:#3D4A80;"
settingStackID = "settingStack"
settingStack = "#settingStack {border: none; border-left:0.5px solid grey;}"
sysSettingStackID = "sysForm"
sysSettingStack = "#sysForm {border: none; border-left:0.5px solid grey;}"
noSideBorder = "border-left:none; border-right:none;"
boldTopBorder = "border-top: 1px solid #545B67;"
boldBottomBorder = "border-bottom: 2px solid #545B67;"
onlyBottomBorder = "border-left:none; border-right:none; border-top:none;"
onlyTopBorder = "border-left:none; border-right:none; border-bottom:none;"
buttonList = "margin-top:0px; border-radius:0px; border:1px solid #fff; padding:3px 0px"
dropDownBtn = "margin-top:0px;border-radius:0px;padding:5px"
checkbox = "margin-left: 10px"
toggleBtnBasic = "border:0.5px solid #000; padding: 8px; text-align:left;"
standardBorder = "border:1px solid #000;"
formBorder = "border:0.5px solid grey;"
warnText = "color: orange"
statusText = "color: black"
errorText = "color: red"
linkStyle = "text-decoration: underline;"
iconBtn = "border:none; background-color:none;"

[asset]
arrowImg = "asset/light/arrow.png"
trashImg = "asset/light/trash.png"
sidebarColor = "asset/light/settingBackground.png"
tabSettings = "asset/light/settings.png"
tabTrash = "asset/light/trash.png"
tabDisk = "asset/light/disk.png"
fileIcon = "asset/light/file.jpeg"
instructionSound = "asset/light/sound.jpeg"
instructionSetting = "asset/light/settings.png"
instructionTranscribe = "asset/light/loading.jpeg"
instructionFile = "asset/light/file.jpeg"
instructionEdit = "asset/light/edit.jpeg"
recordStop = "asset/light/stop.png"
recordPlay = "asset/light/play.png"
downImg = "asset/light/down.png"
rightImg = "asset/light/right.png"
homeBackground = "asset/light/background.png"
subPageBackground = "asset/light/backgroundSubPages.png"
sideBarBackground = "asset/light/sidebarBackground.png"
hilLabLogo = "asset/light/hillogo.png"
transcribing = "asset/light/gbloading.gif"
endRecording = "asset/light/endRecording.png"
