## contains values for the dark mode color theme
[colors] 
##dark mode button colors
##secondary button color, used in save, continue, and get started buttons
SECONDARY_BUTTON = "#76BD46"
##cancel and quit button color
CANCEL_QUIT      = "#FB7C6A"
##highlight background color, primarily used in the background of the file table
HIGHLIGHT        = "#4A6680"
##color of the header of the file table
TABLE_HEADER     = "#4A6680"
##main button color, used in most continue and main menu buttons
PRIMARY_BUTTON   = "#027BFE"
##scroll bar 
SCORLL_BAR       = "#4A6680"
##primary contrast color: white in dark mode
PRIMARY_INTENSE  = "#FFFFFF"
##low contrast- gray color close to black
LOW_CONTRAST     = "#686C71"
##low contrast- gray color less close to black
LOW_CONTRAST2    = "#F0F6F9"
##outline of the file table
OUTLINE          = "#F0F6F9"
GREYDARK         = "#F0F6F9"
##file table border
BORDER           = "#797979"
##high contrast color
GREYEXTRALIGHT   = "#F0F6F9"
##main text
MAIN_TEXT        = "#FFFFFF"
##main background color
MAIN_BACKGROUND  = "#222C3A"
##secondary background color, used in the background of popups and the upload page
SUB_BACKGROUND   = "#35495F"
##highest contrast- white in dark mode
WHITE            = "#FFFFFF"
##color for table border 
TABLE_BORDER     = "#35495F"   

INPUT_TEXT       = "#FFFFFF"
INPUT_BORDER     = "#7F8487"
INPUT_BACKGROUND = "#7F8487"



[styleSheet]
## dark mode style sheet values, to be set as css by elements
basic             = "background-color: #000; color: #fff"
goToMain          = "border:none; color:#D2E4EE;"
settingStackID    = "settingStack"
settingStack      = "#settingStack {border: none; border-left:0.5px solid #EBEBEB;}"
sysSettingStackID = "sysForm"
sysSettingStack   = "#sysForm {border: none; border-left:0.5px solid #EBEBEB;}"
noSideBorder      = "border-left:none; border-right:none;"
boldTopBorder     = "border-top: 1px solid #EBEBEB;"
boldBottomBorder  = "border-bottom: 2px solid #EBEBEB;"
onlyBottomBorder  = "border-left:none; border-right:none; border-top:none;"
onlyTopBorder     = "border-left:none; border-right:none; border-bottom:none;"
buttonList        = "margin-top:0px; border-radius:0px; border:1px solid #FFFFFF; padding:3px 0px"
dropDownBtn       = "margin-top:0px;border-radius:0px;padding:5px"
checkbox          = "margin-left: 10px"
toggleBtnBasic    = "border:0.5px solid #EBEBEB; padding: 8px; text-align:left;"
standardBorder    = "border:1px solid #EBEBEB;"
formBorder        = "border:0.5px solid EBEBEB;"
warnText          = "color: orange"
statusText        = "color: black"
errorText         = "color: red"
linkStyle         = "text-decoration: underline;"
iconBtn           = "border:none; background-color:none;"


[asset]
## dark mode assets
arrowImg              = "asset/dark/arrow.png"
trashImg              = "asset/dark/trash.png"
sidebarColor          = "asset/dark/settingBackground.png"
tabSettings           = "asset/dark/settings.png"
tabTrash              = "asset/dark/trash.png"
tabDisk               = "asset/dark/disk.png"
fileIcon              = "asset/dark/file.jpeg"
instructionSound      = "asset/dark/sound.jpeg"
instructionSetting    = "asset/dark/settings.png"
instructionTranscribe = "asset/dark/loading.jpeg"
instructionFile       = "asset/dark/file.jpeg"
instructionEdit       = "asset/dark/edit.jpeg"
recordStop            = "asset/dark/stop.png"
recordPlay            = "asset/dark/play.png"
downImg               = "asset/dark/down.png"
rightImg              = "asset/dark/right.png"
homeBackground        = "asset/dark/background.png"
subPageBackground     = "asset/dark/backgroundSubPages.png"
sideBarBackground     = "asset/dark/sidebarBackground.png"
hilLabLogo            = "asset/dark/hillogo.png"
transcribing          = "asset/dark/gbloading.gif"
endRecording          = "asset/dark/endRecording.png"
