[colors]
SECONDARY_BUTTON = "#212F3E"
CANCEL_QUIT      = "#721000"
HIGHLIGHT        = "#BED8D7"
TABLE_HEADER     = "#729A9F"
PRIMARY_BUTTON   = "#212F3E"
PRIMARY_INTENSE  = "#293241"
LOW_CONTRAST     = "#AFABA9"
LOW_CONTRAST2    = "#91969D"
OUTLINE          = "#767C85"
SCROLL_BAR       = "#729A9F"
GREYDARK         = "#545B67"
BORDER           = "#484847"
GREYEXTRALIGHT   = "#F0F6F9"
MAIN_TEXT        = "#000000"
MAIN_BACKGROUND  = "#E9EAE7"
SUB_BACKGROUND   = "#729A9F"
WHITE            = "#FFFFFF"
TABLE_BORDER     = "#484847"
INPUT_TEXT       = "#000000"
INPUT_BORDER     = "#000000"
INPUT_BACKGROUND = "#FFFFFF"
LINK             = "#729A9F"
LINKLIGHT        = "#729A9F"

[styleSheet]
basic             = "background-color: #fff; color: #000;"
goToMain          = "border:none; color:#fff;"
settingStackID    = "settingStack"
settingStack      = "#settingStack {border: none; border-left:0.5px solid grey;}"
sysSettingStackID = "sysForm"
sysSettingStack   = "#sysForm {border: none; border-left:0.5px solid grey;}"
noSideBorder      = "border-left:none; border-right:none;"
boldTopBorder     = "border-top: 1px solid #545B67;"
boldBottomBorder  = "border-bottom: 2px solid #545B67;"
onlyBottomBorder  = "border-left:none; border-top:none; border-right: 0.5px solid #545B67;"
onlyTopBorder     = "border-left:none; border-right:none;"
buttonList        = "margin-top:0px; border-radius:0px; border:1px solid #fff; padding:3px 0px;"
dropDownBtn       = "margin-top:0px;border-radius:0px;padding:5px;"
checkbox          = "margin-left: 10px;"
toggleBtnBasic    = "border:0.5px solid #000; padding: 8px; text-align:left;"
standardBorder    = "border:1px solid #000;"
formBorder        = "border:0.5px solid grey;"
warnText          = "color: orange;"
statusText        = "color: black;"
errorText         = "color: red;"
linkStyle         = "text-decoration: underline;"
iconBtn           = "border:none; background-color:none;"
INPUT_TEXT        = " color: #000000; border: 1px solid #000000; background-color: #FFFFFF;border-radius:7px;"
COMBO_BOX         = "QComboBox {background-color: #FFFFFF; text-align:center; color:#000000; border:1px solid #000000; margin: 5px; padding: 3px 12px 3px 12px; border-radius: 7px; margin: 5px;} {color: #000; background-color:#fff;}"
FILE_TABLE        = "{background-color: #E9EAE7; color:#000000; border: 0.5px solid #484847;}"
TABLE_HEADER      = "background-color:#729A9F; font-size:11px; font-family:Raleway; color:#293241;"
SCROLL_BAR        = "background-color:#729A9F; border: 1px solid #E9EAE7;"
MESSAGE_BOX       = "color: #000000;"
MESSAGE_BOX_BTN   = "color: #000;"
PROGRESS_BAR      = "QSlider::groove:horizontal { border: 1px solid #bbb; background: #212F3E; height: 10px; border-radius: 4px;} QSlider::add-page:horizontal { background: #F0F6F9; border: 1px solid #777; height: 10px; border-radius: 4px;} QSlider::handle:horizontal { background: qlineargradient(x1:0, y1:0, x2:1, y2:1,stop:0 #eee, stop:1 #ccc); border: 1px solid #777;width: 13px; margin-top: -2px; margin-bottom: -2px; border-radius: 4px;}"
STANDARD_LINE_EDIT = "QLineEdit {padding: 5px; border-radius: 5px; border: 1px solid #000; color: #000; background-color:#fff;}"
TABLE_LIST = "background-color: #E9EAE7; border:none; margin:0px;"

[asset]
arrowImg              = "asset/light/arrow.png"
trashImg              = "asset/light/trash.png"
sidebarColor          = "asset/light/settingBackground.png"
tabSettings           = "asset/light/settings.png"
tabTrash              = "asset/light/trash.png"
tabDisk               = "asset/light/disk.png"
fileIcon              = "asset/light/file.png"
instructionSound      = "asset/light/sound.png"
instructionSetting    = "asset/light/settings.png"
instructionTranscribe = "asset/light/loading.png"
instructionFile       = "asset/light/file.png"
instructionEdit       = "asset/light/edit.png"
recordStop            = "asset/light/stop.png"
recordPlay            = "asset/light/play.png"
downImg               = "asset/light/down.png"
rightImg              = "asset/light/right.png"
homeBackground        = "asset/light/background.png"
subPageBackground     = "asset/light/backgroundSubPages.png"
sideBarBackground     = "asset/light/sidebarBackground.png"
hilLabLogo            = "asset/light/hillogo.png"
transcribing          = "asset/light/gbloading.gif"
endRecording          = "asset/light/endRecording.png"
pluginBadge           = "asset/light/badge.png"
hover                 = "asset/light/hover.png"
unchecked             = "asset/light/unchecked.png"
checked               = "asset/light/checked.png"
tableDetail           = "asset/light/tableDetail.png"
tableRemove           = "asset/light/tableRemove.png"
tableSource           = "asset/light/tableSource.png"
tableOutput           = "asset/light/tableOutput.png"
tableEdit             = "asset/light/tableEdit.png"
info                  = "asset/light/info.png"