[colors]
SECONDARY_BUTTON = "#729A9F"
CANCEL_QUIT      = "#A25952"
HIGHLIGHT        = "#729A9F"
TABLE_HEADER     = "#C3D7D7"
PRIMARY_BUTTON   = "#729A9F"
SCROLL_BAR       = "#AFABA9"
PRIMARY_INTENSE  = "#1D303F"
LOW_CONTRAST     = "#AFABA9"
LOW_CONTRAST2    = "#5B5B5B"
OUTLINE          = "#F0F6F9"
GREYDARK         = "#F0F6F9"
BORDER           = "#797979"
GREYEXTRALIGHT   = "#F0F6F9"
MAIN_TEXT        = "#FFFFFF"
MAIN_BACKGROUND  = "#1D303F"
SUB_BACKGROUND   = "#AFABA9"
WHITE            = "#FFFFFF"
TABLE_BORDER     = "#AFABA9"
INPUT_TEXT       = "#000000"
INPUT_BORDER     = "#363636"
INPUT_BACKGROUND = "#CECECE"
LINK             = "#729A9F"
LINKLIGHT        = "#729A9F"

[styleSheet]
basic              = "background-color: #1D303F; color: #fff"
goToMain           = "border:none; color:#D2E4EE;"
settingStackID     = "settingStack"
settingStack       = "#settingStack {border: none; border-left:0.5px solid #EBEBEB;}"
sysSettingStackID  = "sysForm"
sysSettingStack    = "#sysForm {border: none; border-left:0.5px solid #EBEBEB;}"
noSideBorder       = "border-left:none; border-right:none;"
boldTopBorder      = "border-top: 1px solid #EBEBEB;"
boldBottomBorder   = "border-bottom: 2px solid #EBEBEB;"
onlyBottomBorder   = "border-left:none; border-top:none; border-right: 0.5px solid #EBEBEB;"
onlyTopBorder      = "border-left:none; border-right:none;"
buttonList         = "margin-top:0px; border-radius:0px; border:1px solid #FFFFFF; padding:3px 0px;"
dropDownBtn        = "margin-top:0px;border-radius:0px;padding:5px;"
checkbox           = "margin-left: 10px;"
toggleBtnBasic     = "border:0.5px solid #EBEBEB; padding: 8px; text-align:left;"
standardBorder     = "border:1px solid #EBEBEB;"
formBorder         = "border:0.5px solid EBEBEB;"
warnText           = "color: orange;"
statusText         = "color: black;"
errorText          = "color: red;"
linkStyle          = "text-decoration: underline;"
iconBtn            = "border:none; background-color:none;"
INPUT_TEXT         = " color: #000000; border: 1px solid #363636; background-color: #CECECE;border-radius:7px;"
COMBO_BOX          = "QComboBox {background-color: #CECECE; text-align:center; color:#000000; border:1px solid #363636; margin: 5px; padding: 3px 12px 3px 12px; border-radius: 7px; margin: 5px;} {color: #fff; background-color:#000;}"
FILE_TABLE         = "{background-color: #1D303F; color:#FFFFFF; border: 0.5px solid #AFABA9;}"
TABLE_HEADER       = "background-color:#C3D7D7; font-size:11px; font-family:Raleway; color:#1D303F;"
SCROLL_BAR         = "background-color:#AFABA9; border: 1px solid #1D303F;"
MESSAGE_BOX        = "color: #FFFFFF;"
MESSAGE_BOX_BTN    = "color: #000;"
PROGRESS_BAR       = "QSlider::groove:horizontal { border: 1px solid #bbb; background: #729A9F; height: 10px; border-radius: 4px;} QSlider::add-page:horizontal { background: #F0F6F9; border: 1px solid #777; height: 10px; border-radius: 4px;} QSlider::handle:horizontal { background: qlineargradient(x1:0, y1:0, x2:1, y2:1,stop:0 #eee, stop:1 #ccc); border: 1px solid #777;width: 13px; margin-top: -2px; margin-bottom: -2px; border-radius: 4px;}"
STANDARD_LINE_EDIT = "QLineEdit {padding: 5px; border-radius: 5px; border: 1px solid #fff; color: #fff; background-color:#000;}"
TABLE_LIST         = "background-color: #1D303F; border:none; margin:0px "
SIDEBAR            = "border-right:0.5px solid #F0F6F9;"

[asset]
arrowImg              = "asset/dark/arrow.png"
trashImg              = "asset/dark/trash.png"
sidebarColor          = "asset/dark/settingBackground.png"
tabSettings           = "asset/dark/settings.png"
tabTrash              = "asset/dark/trash.png"
tabDisk               = "asset/dark/disk.png"
fileIcon              = "asset/dark/file.png"
instructionSound      = "asset/dark/sound.png"
instructionSetting    = "asset/dark/settings.png"
instructionTranscribe = "asset/dark/loading.png"
instructionFile       = "asset/dark/file.png"
instructionEdit       = "asset/dark/edit.png"
recordStop            = "asset/dark/stop.png"
recordPlay            = "asset/dark/play.png"
downImg               = "asset/dark/down.png"
rightImg              = "asset/dark/right.png"
homeBackground        = "asset/dark/background.png"
subPageBackground     = "asset/dark/backgroundSubPages.png"
sideBarBackground     = "asset/dark/sidebarBackground.png"
hilLabLogo            = "asset/dark/hillogo.png"
transcribing          = "asset/dark/gbloading.gif"
endRecording          = "asset/dark/endRecording.png"
pluginBadge           = "asset/dark/badge.png"
hover                 = "asset/dark/hover.png"
unchecked             = "asset/dark/unchecked.png"
checked               = "asset/dark/checked.png"
tableDetail           = "asset/dark/tableDetail.png"
tableRemove           = "asset/dark/tableRemove.png"
tableSource           = "asset/dark/tableSource.png"
tableOutput           = "asset/dark/tableOutput.png"
tableEdit             = "asset/dark/tableEdit.png"
info                  = "asset/dark/info.png"
