## contains values for the dark mode color theme
[colors] 
##dark mode button colors
##secondary button color, used in save, continue, and get started buttons
SECONDARY_BUTTON = "#729A9F"
##cancel and quit button color
CANCEL_QUIT      = "#A25952"
##highlight background color, primarily used in the background of the file table
HIGHLIGHT        = "#729A9F"
##color of the header of the file table
TABLE_HEADER     = "#C3D7D7"
##main button color, used in most continue and main menu buttons
PRIMARY_BUTTON   = "#729A9F"
##scroll bar 
SCROLL_BAR       = "#AFABA9"
##primary contrast color: white in dark mode
PRIMARY_INTENSE  = "#1D303F"
##low contrast- gray color close to black
LOW_CONTRAST     = "#686C71"
##low contrast- gray color less close to black
LOW_CONTRAST2    = "#5B5B5B"
##outline of the file table
OUTLINE          = "#F0F6F9"
GREYDARK         = "#F0F6F9"
##file table border
BORDER           = "#797979"
##high contrast color
GREYEXTRALIGHT   = "#F0F6F9"
##main text
MAIN_TEXT        = "#FFFFFF"
##main background color
MAIN_BACKGROUND  = "#1D303F"
##secondary background color, used in the background of popups and the upload page
SUB_BACKGROUND   = "#AFABA9"
##highest contrast- white in dark mode
WHITE            = "#FFFFFF"
##color for table border 
TABLE_BORDER     = "#AFABA9"   

INPUT_TEXT       = "#000000"
INPUT_BORDER     = "#363636"
INPUT_BACKGROUND = "#CECECE"
LINK             = "#729A9F"
LINKLIGHT        = "#729A9F"




[styleSheet]
## dark mode style sheet values, to be set as css by elements
basic             = "background-color: #1D303F; color: #fff"
goToMain          = "border:none; color:#D2E4EE;"
settingStackID    = "settingStack"
settingStack      = "#settingStack {border: none; border-left:0.5px solid #EBEBEB;}"
sysSettingStackID = "sysForm"
sysSettingStack   = "#sysForm {border: none; border-left:0.5px solid #EBEBEB;}"
noSideBorder      = "border-left:none; border-right:none;"
boldTopBorder     = "border-top: 1px solid #EBEBEB;"
boldBottomBorder  = "border-bottom: 2px solid #EBEBEB;"
onlyBottomBorder  = "border-left:none; border-top:none; border-right: 0.5px solid #EBEBEB;"
onlyTopBorder     = "border-left:none; border-right:none;"
buttonList        = "margin-top:0px; border-radius:0px; border:1px solid #FFFFFF; padding:3px 0px;"
dropDownBtn       = "margin-top:0px;border-radius:0px;padding:5px;"
checkbox          = "margin-left: 10px;"
toggleBtnBasic    = "border:0.5px solid #EBEBEB; padding: 8px; text-align:left;"
standardBorder    = "border:1px solid #EBEBEB;"
formBorder        = "border:0.5px solid EBEBEB;"
warnText          = "color: orange;"
statusText        = "color: black;"
errorText         = "color: red;"
linkStyle         = "text-decoration: underline;"
iconBtn           = "border:none; background-color:none;"
INPUT_TEXT        = " color: #000000; border: 1px solid #363636; background-color: #CECECE;"
COMBO_BOX         = "QComboBox {background-color: #CECECE; text-align:center; color:#000000; border:1px solid #363636; margin: 5px; padding: 3px 12px 3px 12px; border-radius: 7px; margin: 5px;}"
FILE_TABLE        = "{background-color: #1D303F; color:#FFFFFF; border: 0.5px solid #AFABA9;}"
TABLE_HEADER      = "background-color:#C3D7D7; font-size:11px; font-family:Raleway; color:#1D303F;"
SCROLL_BAR        = "background-color:#AFABA9; border: 1px solid #1D303F;"
MESSAGE_BOX       = "color: #FFFFFF;"
MESSAGE_BOX_BTN   = "color: #000;"
PROGRESS_BAR      = "QSlider::groove:horizontal { border: 1px solid #bbb; background: #729A9F; height: 10px; border-radius: 4px;} QSlider::add-page:horizontal { background: #F0F6F9; border: 1px solid #777; height: 10px; border-radius: 4px;} QSlider::handle:horizontal { background: qlineargradient(x1:0, y1:0, x2:1, y2:1,stop:0 #eee, stop:1 #ccc); border: 1px solid #777;width: 13px; margin-top: -2px; margin-bottom: -2px; border-radius: 4px;}"


[asset]
## dark mode assets
arrowImg              = "asset/dark/arrow.png"
trashImg              = "asset/dark/trash.png"
sidebarColor          = "asset/dark/settingBackground.png"
tabSettings           = "asset/dark/settings.png"
tabTrash              = "asset/dark/trash.png"
tabDisk               = "asset/dark/disk.png"
fileIcon              = "asset/dark/file.png"
instructionSound      = "asset/dark/sound.png"
instructionSetting    = "asset/dark/settings.png"
instructionTranscribe = "asset/dark/loading.png"
instructionFile       = "asset/dark/file.png"
instructionEdit       = "asset/dark/edit.png"
recordStop            = "asset/dark/stop.png"
recordPlay            = "asset/dark/play.png"
downImg               = "asset/dark/down.png"
rightImg              = "asset/dark/right.png"
homeBackground        = "asset/dark/background.png"
subPageBackground     = "asset/dark/backgroundSubPages.png"
sideBarBackground     = "asset/dark/sidebarBackground.png"
hilLabLogo            = "asset/dark/hillogo.png"
transcribing          = "asset/dark/gbloading.gif"
endRecording          = "asset/dark/endRecording.png"
pluginBadge           = "asset/dark/badge.png"
hover                 = "asset/dark/hover.png"
unchecked             = "asset/dark/unchecked.png"
checked               = "asset/dark/checked.png"
tableDetail           = "asset/light/tableDetail.png"
tableRemove           = "asset/light/tableRemove.png"
tableSource           = "asset/light/tableSource.png"
tableOutput           = "asset/light/tableOutput.png"
tableEdit             = "asset/light/tableEdit.png"
info                  = "asset/dark/info.png"