[colors]
SECONDARY_BUTTON = "#BED8D7"
CANCEL_QUIT = "#A25952"
HIGHLIGHT = "#729A9F"
TABLE_HEADER = "#C3D7D7"
PRIMARY_BUTTON = "#729A9F"
SCROLL_BAR = "#AFABA9"
PRIMARY_INTENSE = "#1D303F"
LOW_CONTRAST = "#686C71"
LOW_CONTRAST2 = "#5B5B5B"
OUTLINE = "#F0F6F9"
GREYDARK = "#5B5B5B"
BORDER = "#797979"
GREYEXTRALIGHT = "#F0F6F9"
MAIN_TEXT = "#FFFFFF"
MAIN_BACKGROUND = "#1D303F"
SUB_BACKGROUND = "#AFABA9"
WHITE = "#FFFFFF"
TABLE_BORDER = "#AFABA9"
INPUT_TEXT = "#000000"
INPUT_BORDER = "#363636"
INPUT_BACKGROUND = "#CECECE"
LINK = "#D1F5F5"
LINKLIGHT = "#D1F5F5"

[styleSheet]
basic = "background-color: #1D303F; color: #fff"
goToMain = "border:none; color:#D2E4EE;"
settingStackID = "settingStack"
settingStack = "#settingStack {border: none; border-left:0.5px solid #EBEBEB;}"
sysSettingStackID = "sysForm"
sysSettingStack = "#sysForm {border: none; border-left:0.5px solid #EBEBEB;}"
noSideBorder = "border-left:none; border-right:none;"
boldTopBorder = "border-top: 1px solid #EBEBEB;"
boldBottomBorder = "border-bottom: 2px solid #EBEBEB;"
onlyBottomBorder = "border-left:none; border-right:none; border-top:none;"
onlyTopBorder = "border-left:none; border-right:none;"
buttonList = "margin-top:0px; border-radius:0px; border:1px solid #FFFFFF; padding:3px 0px"
dropDownBtn = "margin-top:0px;border-radius:0px;padding:5px"
checkbox = "margin-left: 10px"
toggleBtnBasic = "border:0.5px solid #EBEBEB; padding: 8px; text-align:left;"
standardBorder = "border:1px solid #EBEBEB;"
formBorder = "border:0.5px solid EBEBEB;"
warnText = "color: orange"
statusText = "color: black"
errorText = "color: red"
linkStyle = "text-decoration: underline;"
iconBtn = "border:none; background-color:none;"

[asset]
arrowImg = "asset/dark/arrow.png"
trashImg = "asset/dark/trash.png"
sidebarColor = "asset/dark/settingBackground.png"
tabSettings = "asset/dark/settings.png"
tabTrash = "asset/dark/trash.png"
tabDisk = "asset/dark/disk.png"
fileIcon = "asset/dark/file.png"
instructionSound = "asset/dark/sound.png"
instructionSetting = "asset/dark/settings.png"
instructionTranscribe = "asset/dark/loading.png"
instructionFile = "asset/dark/file.png"
instructionEdit = "asset/dark/edit.png"
recordStop = "asset/dark/stop.png"
recordPlay = "asset/dark/play.png"
downImg = "asset/dark/down.png"
rightImg = "asset/dark/right.png"
homeBackground = "asset/dark/background.png"
subPageBackground = "asset/dark/backgroundSubPages.png"
sideBarBackground = "asset/dark/sidebarBackground.png"
hilLabLogo = "asset/dark/hillogo.png"
transcribing = "asset/dark/gbloading.gif"
endRecording = "asset/dark/endRecording.png"
