# path to config_gui files with backend data
[backend]
gailBotData          = "config_gui/backend/gailbot.toml"
workSpaceData        = "config_gui/backend/workSpace.toml"
defaultWorkSpaceData = "config_gui/backend/defaultWorkSpace.toml"
fileManageData       = "config_gui/backend/fileManage.toml"
backendroot          = "configs/confs/toplevel/user_root.toml" 
# backendroot          = "gailbot/configs/confs/toplevel/user_root.toml" 

# path to config_gui files with style data
[style]
dimension       = "config_gui/style/dimension.toml"
fontFamily      = "config_gui/style/font/fontFamily.toml"
currentColor    = "config_gui/style/color/color.toml"
darkColor       = "config_gui/style/color/colorDark.toml"
lightColor      = "config_gui/style/color/colorLight.toml"
currentFontSize = "config_gui/style/font/fontSize.toml"
largeFontSize   = "config_gui/style/font/fontSizeLarge.toml"
smallFontSize   = "config_gui/style/font/fontSizeSmall.toml"
mediumFontSize  = "config_gui/style/font/fontSizeMedium.toml"

# path to config_gui files with text data
[text]
string          = "config_gui/text/text.toml"
form            = "config_gui/text/forms.toml"
about           = "config_gui/text/about.toml"

# path to config_gui files with the preset data 
[setting]
profilePreset   = "config_gui/setting/profileValues.toml"
systemSetting   = "config_gui/setting/systemSettingValues.toml"
defaultSetting   = "config_gui/setting/defaultSetting.toml"
