## contains values for the dark mode color theme
[colors] 
## dark mode button colors
SECONDARY_BUTTON = "#76BD46"
CANCEL_QUIT      = "#FB7C6A"
HIGHLIGHT        = "#4A6680"
TABLE_HEADER     = "#75A9B6"
PRIMARY_BUTTON   = "#027BFE"
PRIMARY_INTENSE  = "#FFFFFF"
LOW_CONTRAST     = "#686C71"
LOW_CONTRAST2    = "#F0F6F9"
OUTLINE          = "#F0F6F9"
GREYDARK         = "#F0F6F9"
BORDER           = "#797979"
GREYEXTRALIGHT   = "#F0F6F9"
MAIN_TEXT        = "#FFFFFF"
MAIN_BACKRGOUND  = "#236372"
SUB_BACKGROUND   = "#236372"
WHITE            = "#FFFFFF"


[styleSheet]
## dark mode style sheet values, to be set as css by elements
basic             = "background-color: #000; color: #fff"
goToMain          = "border:none; color:#D2E4EE;"
settingStackID    = "settingStack"
settingStack      = "#settingStack {border: none; border-left:0.5px solid #EBEBEB;}"
sysSettingStackID = "sysForm"
sysSettingStack   = "#sysForm {border: none; border-left:0.5px solid #EBEBEB;}"
noSideBorder      = "border-left:none; border-right:none;"
boldTopBorder     = "border-top: 1px solid #EBEBEB;"
boldBottomBorder  = "border-bottom: 2px solid #EBEBEB;"
onlyBottomBorder  = "border-left:none; border-right:none; border-top:none;"
onlyTopBorder     = "border-left:none; border-right:none; border-bottom:none;"
buttonList        = "margin-top:0px; border-radius:0px; border:1px solid #FFFFFF; padding:3px 0px"
dropDownBtn       = "margin-top:0px;border-radius:0px;padding:5px"
checkbox          = "margin-left: 10px"
toggleBtnBasic    = "border:0.5px solid #EBEBEB; padding: 8px; text-align:left;"
standardBorder    = "border:1px solid #EBEBEB;"
formBorder        = "border:0.5px solid EBEBEB;"
warnText          = "color: orange"
statusText        = "color: black"
errorText         = "color: red"
linkStyle         = "text-decoration: underline;"
iconBtn           = "border:none; background-color:none;"


[asset]
## dark mode assets
arrowImg              = "asset/light/arrow.png"
trashImg              = "asset/light/trash.png"
sidebarColor          = "asset/light/settingBackground.png"
tabSettings           = "asset/light/settings.png"
tabTrash              = "asset/light/trash.png"
tabDisk               = "asset/light/disk.png"
fileIcon              = "asset/light/file.jpeg"
instructionSound      = "asset/light/sound.jpeg"
instructionSetting    = "asset/light/settings.png"
instructionTranscribe = "asset/light/loading.jpeg"
instructionFile       = "asset/light/file.jpeg"
instructionEdit       = "asset/light/edit.jpeg"
recordStop            = "asset/light/stop.png"
recordPlay            = "asset/light/play.png"
downImg               = "asset/light/down.png"
rightImg              = "asset/light/right.png"
homeBackground        = "asset/dark/background.png"
subPageBackground     = "asset/dark/backgroundSubPages.png"
sideBarBackground     = "asset/dark/sidebarBackground.png"
hilLabLogo            = "asset/light/hillogo.png"
transcribing          = "asset/light/gbloading.gif"
