## config file with all style value
[colors] 
SECONDARY_BUTTON = "#6E9B87" 
CANCEL_QUIT = "#EE6C4D"
HIGHLIGHT = "#F0F6F9"
TABLE_HEADER = "#D2E4EE"
PRIMARY_BUTTON = "#3D4A80"
PRIMARY_INTENSE = "#293241"
LOW_CONTRAST = "#EBEBEB"
LOW_CONTRAST2 = "#91969D"
OUTLINE = "#767C85"
GREYDARK = "#545B67" 
BORDER = "#797979"
GREYEXTRALIGHT = "#F0F6F9"
MAIN_TEXT = "#000000"
MAIN_BACKRGOUND = "#FFFFFF"
SUB_BACKGROUND  = "#F0F6F9"
WHITE = "#FFFFFF"


[styleSheet]
basic               = "background-color: #fff; color: #000"
goToMain            = "border:none; color:#3D4A80;"
settingStackID      ="settingStack"
settingStack        = "#settingStack {border: none; border-left:0.5px solid grey;}"
sysSettingStackID   = "sysForm"
sysSettingStack     = "#sysForm {border: none; border-left:0.5px solid grey;}"
noSideBorder        = "border-left:none; border-right:none;"
boldTopBorder       = "border-top: 1px solid #545B67;"
boldBottomBorder    = "border-bottom: 2px solid #545B67;"
onlyBottomBorder    = "border-left:none; border-right:none; border-top:none;"
onlyTopBorder       = "border-left:none; border-right:none; border-bottom:none;"
buttonList          = "margin-top:0px; border-radius:0px; border:1px solid #fff; padding:3px 0px"
dropDownBtn         = "margin-top:0px;border-radius:0px;padding:5px"
checkbox            = "margin-left: 10px"
toggleBtnBasic      = "border:0.5px solid #000; padding: 8px; text-align:left;"
standardBorder      = "border:1px solid #000;"
formBorder          = "border:0.5px solid grey;"
warnText            = "color: orange"
statusText          = "color: black"
errorText           = "color: red"
linkStyle           = "text-decoration: underline;"
iconBtn             = "border:none; background-color:none;"


[asset]
arrowImg = "/light/arrow.png"
trashImg = "/light/trash.png"
headerFont =  "view/asset/Raleway.ttf"
clockFont = "view/asset/digital.ttf"
sidebarColor = "/light/settingBackground.png"
tabSettings = "/light/settings.png"
tabTrash = "/light/trash.png"
tabDisk = "/light/disk.png"
fileIcon = "/light/file.jpeg"
instructionSound = "/light/sound.jpeg"
instructionSetting = "/light/settings.png"
instructionTranscribe = "/light/loading.jpeg"
instructionFile = "/light/file.jpeg"
instructionEdit = "/light/edit.jpeg"
recordStop = "/light/stop.png"
recordPlay = "/light/play.png"
downImg = "/light/down.png"
rightImg = "/light/right.png"
homeBackground = "/light/background.png"
subPageBackground = "/light/backgroundSubPages.png"
sideBarBackground = "/light/sidebarBackground.png"
hilLabLogo = "/light/hillogo.png"
transcribing = "view/asset/light/gbloading.gif"