# conatins the value for dimension data
[dimension]
WINMAXWIDTH         = 1100
WINMAXHEIGHT        = 900
BTNWIDTH            = 150
BTNHEIGHT           = 40
SBTNWIDTH           = 100
SBTNHEIGHT          = 30
LBTNWIDTH           = 200
CONSOLEWIDTH        = 1000
CONSOLEHEIGHT       = 300
STATUSWIDTH         = 900
STATUSHEIGHT        = 30
INPUTWIDTH          = 200
INPUTHEIGHT         = 30
ICONBTN             = 50
SMALLICONBTN        = 30
TABLEWIDTH          = 900
TABLEMINHEIGHT      = 300
TABLECONTAINERWIDTH = 920
PROGRESSBARWIDTH    = 450
PROGRESSBARHEIGHT   = 40
LARGEDIALOGWIDTH    = 950
LARGEDIALOGHEIGHT   = 720
TOGGLEBARMAXWIDTH   = 700
TOGGLEBARMINWIDTH   = 550
TOGGLEVIEWOFFSET    = 20
STANDARDSPACING     = 10
SIDEBAR             = 200
FORMWIDTH           = 650
FORMMINHEIGHT       = 550
FORMMAXHEIGHT       = 720
DEFAULTTABHEIGHT    = 300
DEFAULTTABWIDTH     = 600
LOGO_WIDTH          = 120
LOGO_HEIGHT         = 40
SMALL_TABLE_WIDTH   = 350
SMALL_TABLE_HEIGHT  = 150
SMALL_SPACING       = 5
MEDIUM_SPACING      = 20
LARGE_SPACING       = 30
WIN_MIN_WIDTH       = 1000
WIN_MIN_HEIGHT      = 780
LARGE_ICON          = 80
OUTPUT_FORM_HEIGHT  = 420
COMBOBOX_HEIGHT     = 40 


[filetable.dimension]
fileUploadPage = [0.07,0.07,0.2,0.15,0.15,0.08,0.08,0.20]
confirmPage    = [0.1,0.35,0.35,0.2]
transcribePage = [0.2, 0.55, 0.25]
successPage    = [0.17, 0.35, 0.25, 0.23]


