[asset]
"arrowImg" = "arrow.png"
"subPageBackgorund" = "backgroundConfirmPage.png"
"trashImg" = "trash.png"
"mainBackground" = "background.png"
headerFont =  "view/asset/Raleway.ttf"
sidebarColor = "settingBackground.png"
tabSettings = "settings.png"
tabTrash = "trash.png"
tabDisk = "disk.png"
fileIcon = "file.jpeg"
instructionSound = "sound.jpeg"
instructionSetting = "settings.png"
instructionTranscribe = "loading.jpeg"
instructionFile = "file.jpeg"
instructionEdit = "edit.jpeg"
recordStop = "stop.png"
recordPlay = "play.png"