# path to config files with backend data
[backend]
gailBotData          = "config/backend/gailbot.toml"
workSpaceData        = "config/backend/workSpace.toml"
defaultWorkSpaceData = "config/backend/defaultWorkSpace.toml"
fileManageData       = "config/backend/fileManage.toml" 

# path to config files with style data
[style]
dimension       = "config/style/dimension.toml"
fontFamily      = "config/style/font/fontFamily.toml"
currentColor    = "config/style/color/color.toml"
darkColor       = "config/style/color/colorDark.toml"
lightColor      = "config/style/color/colorLight.toml"
currentFontSize = "config/style/font/fontSize.toml"
largeFontSize   = "config/style/font/fontSizeLarge.toml"
smallFontSize   = "config/style/font/fontSizeSmall.toml"
mediumFontSize  = "config/style/font/fontSizeMedium.toml"

# path to config files with text data
[text]
string          = "config/text/text.toml"
form            = "config/text/forms.toml"
about           = "config/text/about.toml"

# path to config files with the preset data 
[setting]
profilePreset   = "config/setting/profileValues.toml"
systemSetting   = "config/setting/settingValues.toml"