[sysColor]
maintext = "#000"
background = "#fff"
subBackground = "#F0F6F9"

[sysImages]
homeBackground = "background.png"
subPageBackground = "backgroundSubPages.png"


[sysFontSize]
body = "14px"

[sysStyleSheet]
basic = "background-color: #fff; color: #000"