[dimension]
WINMAXWIDTH = 1100
WINMAXHEIGHT = 900
BTNWIDTH = 150
BTNHEIGHT = 40
SBTNWIDTH = 100
SBTNHEIGHT  = 30 
LBTNWIDTH = 200
CONSOLEWIDTH = 1000
CONSOLEHEIGHT = 300
STATUSWIDTH = 900
STATUSHEIGHT = 30 
INPUTWIDTH = 200
INPUTHEIGHT = 30
ICONBTN = 50
SMALLICONBTN = 30
TABLEWIDTH = 900
TABLEMINHEIGHT = 300
TABLECONTAINERWIDTH = 920
PROGRESSBARWIDTH = 400
PROGRESSBARHEIGHT = 40
LARGEDIALOGWIDTH = 850
LARGEDIALOGHEIGHT = 800
TOGGLEBARMAXWIDTH = 700
TOGGLEBARMINWIDTH = 550
TOGGLEVIEWOFFSET = 20
STANDARDSPACING = 10 
SIDEBAR = 200
FORMWIDTH = 650
FORMMINHEIGHT = 550
FORMMAXHEIGHT = 740
DEFAULTTABHEIGHT = 300
DEFAULTTABWIDTH = 600
LOGO_WIDTH = 120
LOGO_HEIGHT = 40

[fontSizes]
BODY = "13px"
TEXT_FIELD = "12px"
SMALL="11px"
LINK = "15px"
HEADER1 = "32px" 
HEADER2  = "24px"
HEADER3  = "18px"
TABLE_ROW = "13px"
DESCRIPTION = "12px"
INSTRUCTION_CAPTION = "14px"
BTN = "14px" 
SETTINGICON = "40px"

[fontFamily]
MAIN       = "Raleway"
OTHER      = "Helvetica"

[filetable.dimension]
fileUploadPage = [0.07,0.07,0.2,0.15,0.15,0.08,0.08,0.2]
confirmPage    = [0.1,0.35,0.25,0.13,0.17]
transcribePage = [0.2, 0.55, 0.25]
successPage    =  [0.17, 0.35, 0.25, 0.23]


