###### form values
["profile form".Plugins]
HiLabSuite = "https://sites.tufts.edu/hilab/files/2022/05/HiLabSuite.zip"

["profile form"."PostTranscribe".General]
"Gap Length" = "0s"
"Turn End Threshold" = "0s"
"Large Pause - Lower Bound" = "0s"

["profile form"."PostTranscribe"."Laghter Settings"]
"Laughter Detection Module bool" = "ON"
"Laughter Probability - Lower Bound" = "0s"
"Laughter Length - Lower Bound" = "0s"

["profile form"."PostTranscribe"."MicroPause Bound"]
"Upper Bound" = "0s"
"Lower Bound" = "0s"

["profile form"."PostTranscribe"."Transcription Model"]
"Beat Transcription Mode bool" = "ON"
"FTO (Floor Transfer offset)Transcription Mode bool" = "ON"
"Syllable Rate mode bool" = "ON"

["profile form"."RequiredSetting"."Output Format".CorpusSettings]
"Corpus name" = "enter corpus name"
"Corpus location" = "enter corpus location"
"Corpus room layout" = "enter corous room layout"
"Corpus situation" = "enter situation"

["profile form"."RequiredSetting"."Output Format"]
"FileFormat" = ["CHART", "TXT", "RTF"]
"Language" = ["English", "French", "Spanish", "German", "Chinese(Madarin)", "Chinese(Cantonese)"]


["profile form"."RequiredSetting".Engine.IBM."1.language model setting"]
"1. language model" = [ "IBM language", "English", "Spanish",]
"2. costum language model" = [ "HRI lab", "None", "Air Force Study",]

["profile form"."RequiredSetting".Engine.IBM."2.Acoustic Model Setting"]
"1. acoustic model setting" = [ "acoustic1", "acoustic2", "acoustic3",]
"2. acoustic model setting(optional)" = [ "1", "2", "3",]

["profile form"."RequiredSetting".Engine.IBM."3.advanced setting"]
"1. Advanced Setting Option 1" = [ "advanced 1", "advanced 2", "advanced 3",]
"2. plugin" = [ "plugin 1", "plugin 2",]

["profile form"."RequiredSetting".Engine.IBM."4.IBM specialised setting"]
"IBM dummy setting" = [ "dummy setting1", "dummy setting2", "dummy setting3",]

["profile form"."RequiredSetting".Engine.CMU."1.language model setting"]
"1. language model" = [ "CMU language", "English", "Spanish",]
"2. costum language model" = [ "CMU costum", "None", "Air Force Study",]

["profile form"."RequiredSetting".Engine.CMU."2.Acoustic Model Setting"]
"1. acoustic model setting" = [ "acoustic1", "acoustic2", "acoustic3",]
"2. acoustic model setting(optional)" = [ "1", "2", "3",]
"3. plugin" = [ "plugin 1", "plugin 2",]

["profile form"."RequiredSetting".Engine.CMU."3.CMU specialised setting"]
"CMU dummy setting" = [ "dummy setting1", "dummy setting2", "dummy setting3",]

["system setting form"."General Setting"]
"Font Size combo" = [ "small", "medium", "big",]
"Color Mode combo" = [ "default", "dark", "light",]
"Large Pause - Lower Bound" = "0s"

["system setting form"."Dummy Setting Options"]
"Dummy on and off bool" = "ON"
"Dummy input" = "dummy"
"Dummy selection mode combo" = [ "selection1", "selection2", "selection3",]

[filetable.header]
"fileUploadPage" = ["Select All", "Type", "Name", "Profile", 
                    "Status", "Date", "Size", "Actions"]
"confirmPage"  = ["Type", "Name", "Profile", "SelectedAction", "Action"]
"transcribePage" = ["Type", "Name", "Progress"]
"successPage"   =  ["Type",  "Name", "Status", "Output"]


[filetable.dimension]
"fileUploadPage" = [0.07,0.07,0.2,0.15,0.15,0.08,0.08,0.2]
"confirmPage"    = [0.1,0.35,0.25,0.13,0.17]
"transcribePage" = [0.2, 0.55, 0.25]
"successPage"   =  [0.17, 0.35, 0.25, 0.23]


