title = "Style configuration"

###### style values
[style.colors] 
GREEN = "#6E9B87"
ORANGE = "#EE6C4D"
BLUEWHITE = "#F0F6F9"
BLUELIGHT = "#D2E4EE"
BLUEMEDIUM = "#3D4A80"
BLUEDARK = "#293241"
GREYLIGHT = "#EBEBEB"
GREYMEDIUM1 = "#91969D"
GREYMEDIUM2 = "#767C85"
GREYDARK = "#545B67"
BORDERGREY = "#797979"
BLACK = "#000000"
WHITE = "#FFFFFF"
GREYEXTRALIGHT = "#F0F6F9"

[style.dimension]
WINMAXWIDTH = 1100
WINMAXHEIGHT = 900
BTNWIDTH = 150
BTNHEIGHT = 40
SBTNWIDTH = 100
SBTNHEIGHT  = 30 
LBTNWIDTH = 200
CONSOLEWIDTH = 1000
CONSOLEHEIGHT = 300
STATUSWIDTH = 900
STATUSHEIGHT = 30 
INPUTWIDTH = 200
INPUTHEIGHT = 30
ICONBTN = 50
SMALLICONBTN = 30
TABLEWIDTH = 900
TABLEMINHEIGHT = 300
TABLECONTAINERWIDTH = 920
PROGRESSBARWIDTH = 400
PROGRESSBARHEIGHT = 40
LARGEDIALOGWIDTH = 850
LARGEDIALOGHEIGHT = 800
TOGGLEBARMAXWIDTH = 700
TOGGLEBARMINWIDTH = 550
TOGGLEVIEWOFFSET = 20
STANDARDSPACING = 10 
SIDEBAR = 200
FORMWIDTH = 650
FORMMINHEIGHT = 550
FORMMAXHEIGHT = 740
DEFAULTTABHEIGHT = 300
DEFAULTTABWIDTH = 600



[style.fontSizes]
BODY = "13px"
TEXT_FIELD = "12px"
SMALL="11px"
LINK = "15px"
HEADER1 = "32px" 
HEADER2  = "24px"
HEADER3  = "18px"
TABLE_ROW = "13px"
DESCRIPTION = "12px"
INSTRUCTION_CAPTION = "14px"
BTN = "14px" 
SETTINGICON = "40px"

[style.fontFamily]
 MAIN       = "Raleway"
 OTHER      = "Helvetica"

[style.styleSheet]
goToMain            = "border:none; color:#3D4A80;"
settingStackID      ="settingStack"
settingStack        = "#settingStack {border: none; border-left:0.5px solid grey;}"
sysSettingStackID   = "sysForm"
sysSettingStack     = "#sysForm {border: none; border-left:0.5px solid grey;}"
noSideBorder        = "border-left:none; border-right:none;"
boldTopBorder       = "border-top: 1px solid #545B67;"
boldBottomBorder    = "border-bottom: 2px solid #545B67;"
onlyBottomBorder    = "border-left:none; border-right:none; border-top:none;"
onlyTopBorder       = "border-left:none; border-right:none; border-bottom:none;"
buttonList          = "margin-top:0px; border-radius:0px; border:1px solid #fff; padding:3px 0px"
dropDownBtn         = "margin-top:0px;border-radius:0px;padding:5px"
checkbox            = "margin-left: 10px"
toggleBtnBasic      =  "border:0.5px solid #000; padding: 8px; text-align:left;"
standardBorder      = "border:1px solid #000;"
formBorder          = "border:0.5px solid grey;"
warnText            = "color: orange"
statusText          = "color: black"
errorText           = "color: red"