title = "Style configuration"

###### style values
[style.colors] 
GREEN = "#6E9B87"
ORANGE = "#EE6C4D"
BLUEWHITE = "#F0F6F9"
BLUELIGHT = "#D2E4EE"
BLUEMEDIUM = "#3D4A80"
BLUEDARK = "#293241"
GREYLIGHT = "#EBEBEB"
GREYMEDIUM1 = "#91969D"
GREYMEDIUM2 = "#767C85"
GREYDARK = "#545B67"
BORDERGREY = "#797979"
BLACK = "#000000"
WHITE = "#FFFFFF"
GREYEXTRALIGHT = "#F0F6F9"

[style.dimension]
WINMAXWIDTH = 1100
WINMAXHEIGHT = 900
BTNWIDTH = 150
BTNHEIGHT = 40
SBTNWIDTH = 100
SBTNHEIGHT  = 30 
LBTNWIDTH = 200
CONSOLEWIDTH = 1000
CONSOLEHEIGHT = 300
STATUSWIDTH = 900
STATUSHEIGHT = 30 
INPUTWIDTH = 200
INPUTHEIGHT = 30
ICONBTN = 50
TABLEWIDTH = 900
TABLEMINHEIGHT = 300
TABLECONTAINERWIDTH = 920
PROGRESSBARWIDTH = 400
PROGRESSBARHEIGHT = 40
LARGEDIALOGWIDTH = 850
LARGEDIALOGHEIGHT = 800

[style.fontSizes]
BODY = "13px"
TEXT_FIELD = "12px"
SMALL="11px"
LINK = "15px"
HEADER1 = "32px" 
HEADER2  = "24px"
HEADER3  = "18px"
TABLE_ROW = "13px"
DESCRIPTION = "12px"
INSTRUCTION_CAPTION = "14px"
BTN = "14px" 
SETTINGICON = "40px"

[style.fontFamily]
 MAIN = "Raleway"
 OTHER = "Helvetica"

[style.styleSheet]
"goToMain" = "border:none; color:#3D4A80;"
"settingStackID" ="settingStack"
"settingStack" = "#settingStack {border: none; border-left:0.5px solid grey;}"
"sysSettingStackID" = "sysForm"
"sysSettingStack" = "#sysForm {border: none; border-left:0.5px solid grey;}"
"noSideBorder" = "border-left:none; border-right:none;"
"boldTopBorder" = "border-top: 1px solid #545B67;"
"boldBottomBorder" = "border-bottom: 2px solid #545B67;"
"onlyBottomBorder" = "border-left:none; border-right:none; border-top:none;"
"onlyTopBorder"  = "border-left:none; border-right:none; border-bottom:none;"
"buttonList" = "margin-top:0px; border-radius:0px; border:1px solid #fff; padding:3px 0px"
"dropDownBtn" = "margin-top:0px;border-radius:0px;padding:5px"

###### form values
["profile form".Plugins]
HiLabSuite = "https://sites.tufts.edu/hilab/files/2022/05/HiLabSuite.zip"

["profile form"."PostTranscribe".General]
"Gap Length" = "0s"
"Turn End Threshold" = "0s"
"Large Pause - Lower Bound" = "0s"

["profile form"."PostTranscribe"."Laghter Settings"]
"Laughter Detection Module bool" = "ON"
"Laughter Probability - Lower Bound" = "0s"
"Laughter Length - Lower Bound" = "0s"

["profile form"."PostTranscribe"."MicroPause Bound"]
"Upper Bound" = "0s"
"Lower Bound" = "0s"

["profile form"."PostTranscribe"."Transcription Model"]
"Beat Transcription Mode bool" = "ON"
"FTO (Floor Transfer offset)Transcription Mode bool" = "ON"
"Syllable Rate mode bool" = "ON"

["profile form"."RequiredSetting"."Output Format".CorpusSettings]
"Corpus name" = "enter corpus name"
"Corpus location" = "enter corpus location"
"Corpus room layout" = "enter corous room layout"
"Corpus situation" = "enter situation"

["profile form"."RequiredSetting"."Output Format"]
"FileFormat" = ["CHART", "TXT", "RTF"]
"Language" = ["English", "French", "Spanish", "German", "Chinese(Madarin)", "Chinese(Cantonese)"]


["profile form"."RequiredSetting".Engine.IBM."1.language model setting"]
"1. language model" = [ "IBM language", "English", "Spanish",]
"2. costum language model" = [ "HRI lab", "None", "Air Force Study",]

["profile form"."RequiredSetting".Engine.IBM."2.Acoustic Model Setting"]
"1. acoustic model setting" = [ "acoustic1", "acoustic2", "acoustic3",]
"2. acoustic model setting(optional)" = [ "1", "2", "3",]

["profile form"."RequiredSetting".Engine.IBM."3.advanced setting"]
"1. Advanced Setting Option 1" = [ "advanced 1", "advanced 2", "advanced 3",]
"2. plugin" = [ "plugin 1", "plugin 2",]

["profile form"."RequiredSetting".Engine.IBM."4.IBM specialised setting"]
"IBM dummy setting" = [ "dummy setting1", "dummy setting2", "dummy setting3",]

["profile form"."RequiredSetting".Engine.CMU."1.language model setting"]
"1. language model" = [ "CMU language", "English", "Spanish",]
"2. costum language model" = [ "CMU costum", "None", "Air Force Study",]

["profile form"."RequiredSetting".Engine.CMU."2.Acoustic Model Setting"]
"1. acoustic model setting" = [ "acoustic1", "acoustic2", "acoustic3",]
"2. acoustic model setting(optional)" = [ "1", "2", "3",]
"3. plugin" = [ "plugin 1", "plugin 2",]

["profile form"."RequiredSetting".Engine.CMU."3.CMU specialised setting"]
"CMU dummy setting" = [ "dummy setting1", "dummy setting2", "dummy setting3",]

["system setting form"."General Setting"]
"Font Size combo" = [ "small", "medium", "big",]
"Color Mode combo" = [ "default", "dark", "light",]
"Large Pause - Lower Bound" = "0s"

["system setting form"."Dummy Setting Options"]
"Dummy on and off bool" = "ON"
"Dummy input" = "dummy"
"Dummy selection mode combo" = [ "selection1", "selection2", "selection3",]

[filetable.header]
"fileUploadPage" = ["Select All", "Type", "Name", "Profile", 
                    "Status", "Date", "Size", "Actions"]
"confirmPage"  = ["Type", "Name", "Profile", "SelectedAction", "Action"]
"transcribePage" = ["Type", "Name", "Progress"]
"successPage"   =  ["Type",  "Name", "Status", "Output"]


[filetable.dimension]
"fileUploadPage" = [0.07,0.07,0.2,0.15,0.15,0.08,0.08,0.2]
"confirmPage"    = [0.1,0.35,0.25,0.13,0.17]
"transcribePage" = [0.2, 0.55, 0.25]
"successPage"   =  [0.17, 0.35, 0.25, 0.23]

[asset]
"arrowImg" = "arrow.png"
"subPageBackgorund" = "backgroundConfirmPage.png"
"trashImg" = "trash.png"
"mainBackground" = "background.png"

[about]
"version" = "1.0.0"
