###### text values 
[links]
HILAB = "https://sites.tufts.edu/hilab"

[TranscribeSuccessText]
mainLabelText = "Transcription Successful"
transcribedFilesText = "Transcribed files and locations:"
moreBtnText = "Process more files"
returnBtnText = "Return to main menu"

[TranscribeProgressText]
mainLabelText = "Transcription in Progress"
loadingText = "Transcribing files..."
inProgressText = "Files in progress:"
cancelText = "Cancel"

[WelcomePageText]
audioInstructionText = "1. Select audio and video files \n or record live in Gailbot"
settingsInstructionText = "2. Apply settings"
transcribeInstructionText = "3. Transcribe"
fileInstructionText = "4. Get a transcribed file"
editInstructionText = "5. Edit settings \n or retranscribe"
welcomeText = "Welcome to GailBot"
captionText = "GailBot is the world's first application that lets you convert audio and\n video files into customizd transcripts."
startBtnText = "Get Started"
instructionText = "How GailBot Works"
resourcesText = "Resources"
tutorialText = "GailBot Beginner Tutorial"
guideText = "GailBot Settings Guide"
gbLinkText = "GailBot.com"
moreInfoText = "For more information visit"

[FileUploadPageText]
header = "Files to Transcribe"
returnMainText = "Return to Main Menu"
recordBtnText = "Record live"
uploadBtnText = "Add From Device"
transcribeBtnText = "Transcribe"
removeBtnText = "Remove All"
settingBtnText = "⚙"
dropText = "Drop File Here to Upload"
chooseLocalText = "Choose From Local"
chooseSetHeader = "select setting profile"
selectSetText = "select settings"
selectPlaceHolderText = "None"
selectFolderText = "Select Folder"
chooseOutPutText = "Choose Output Directory"
fileFilter = ["audio file (*.wav)","directory (/)"]
removeWarnText = "Remove all files?"

[RecordPageText]
basic = "Basic"
filename = "Filename"
mp3 = "MP3"
wav = "WAV"
format = "Audio Format"
advanced = "Advanced"
rate = "Recording Rate (Hertz)"
duration = "Max Recording Duration"
cancel = "Cancel"
start = "Start Recording"
test = "Test MicroPhone"
recSet = "Recording Settings"
record = "Record Audio File"
end = "End Recording"

[ProfilePageText]
cancelBtn = "Cancel"
saveBtn = "Save and Exit"
newProfileBtn = "Create New Profile"
reuquiredSetBtn = "Required Settings"
postSetBtn = "Post-Transcription Settings"
newPluginBtn = "Add New Plugin"
pluginSetBtn = "Plugin Setting"
postSetHeader = "Post-Transcription Settings"
postSetCaption = "These settings are applied after the file is created."
requiredSetHeader =  "Required Settings"
requiredSetCaption =  "These settings are required before transcription and cannot be edited after transcription."
pluginHeader = "Choose Plugins"
pluginCaption = "These plugins are applied to transcription process"

[SystemSettingPage]
header = "System Setting"
caption = "These settings are applied for system setting"
cancelBtn = "Cancel"
saveBtn = "Save and Exit"

[ConfirmTranscriptionPageText]
confirmLabel = "Confirm Files and Settings"
confirm = "Confirm"
cancel = "Cancel"

[RecordInProgressPageText]
start = "Start Recording"
cancel = "Cancel"
end = "End Recording"

[filetable.header]
"fileUploadPage" = ["Select All", "Type", "Name", "Profile", 
                    "Status", "Date", "Size", "Actions"]
"confirmPage"    = ["Type", "Name", "Profile", "SelectedAction", "Action"]
"transcribePage" = ["Type", "Name", "Progress"]
"successPage"    =  ["Type",  "Name", "Status", "Output"]


[CreateNewProfilePageText]  
confirmProfileNameBtn = "Start"
emptyNameMsg = "The profile name cannot be empty"
emptyUserMsg = "Please enter user name and password"
engineSettingHeader = "Speech to text settings"
outputSettingHeader =  "Output format settings"
cofirmBtn = "confirm"

[ChooseFileTabText]
WindowTitle = "Upload File"
TabTitle    = "Add New File"
TabHeader1  = "add file"
TabHeader2  = "choose setting"
TabHeader3  = "select output"

[WindowTitle]
consoleWindow = "Console Window"

[CreateNewProfileTabText]
WindowTitle = "Create New Profile"
TabTitle = "Create New Profile"
TabHeader1 = "Profile Name"
TabHeader2 = "Basic Settings"
TabHeader3 = "Optional Settings"
TabHeader4 = "Output File Format Setting"
TabHeader5 = "Post Transcribtion Settion"
TabHeader6 = "Plugin Setting"

[MainStackText]
ProfileSetting = "Porfile Setting"
SystemSetting  = "System Setting"

[OutputFormatForm]
header = "Output File Format"
CorpuFormHeader = "Corpus Settings"
LanguageHeader  = "language"
FileHeaderView = "File Header Views"
FileFormatHeader = "File Format"
SpeakerHeader = "Number of Speaker"
TextWrap = "Text-Wrapping"

[RequiredSettingForm]
engineSetHeader = "Speech to text settings"
outputSetHeader = "Output File Format Settings"

[MenuBar]
console = "Console"
open = "Open"
close = "close"

####widgets
[btnText]
on = "ON"
off = "OFF"
icon = "iconButton"
right = "right.png"
down = "down.png"

[fileTableText]
default = "Default"
delete = "Delete"
changeSet = "Change Setting"
profileDet = "Profile Details"

[multipleComboText]
username = "Username"
password = "Password"

[popUpText]
leftArr = "▶"
rightArr = "◀"
finish = "Finish"
window = "File Info"

[tableText]
location = "Change Location"
postSettings = "Post Transcribe Setting"
save = "Save"
transBy = "Transcribed by: "
transOn = "Trancribed on: "
inDir = "In this directory"
abtDir = "About this directory"