import logging.config 
import hmmlearn
import certifi
import pytorch_lightning
import pytorch_metric_learning
import whisper 
import huggingface_hub
import ffmpeg
import pyannote.audio 
import pyannote.pipeline
import ffmpeg
import sklearn.utils
import sklearn
from speechbrain import utils 
import torch
import torchvision
import torchaudio 
import librosa.util
import urllib
import sklearn.metrics._pairwise_distances_reduction  
import  pyannote.audio.pipelines
import hmmlearn.hmm 
import pytorch_metric_learning.losses
