import logging.config 
import hmmlearn
import certifi
import pytorch_lightning
import pytorch_metric_learning
import whisper 
import huggingface_hub
import ffmpeg
import pyannote.audio 
import pyannote.pipeline
import ffmpeg
import sklearn
import sklearn
from speechbrain import utils 
import librosa
import urllib
import sklearn.metrics._pairwise_distances_reduction  
import  pyannote.audio
import hmmlearn 
import pytorch_metric_learning.losses
import syllables
import certifi
import PIL
