# contains relative paths for the output of gailbot
[output]
transcribe_result = "result/transcription"
analysis_result = "result/analysis"
format_result = "result/format"
media_file = "media"

# TODO: delete the root from other paths
[workspace]
root = "gailbot_workspace"

# contains relative paths for the directory storing the gailbot data
[workspace.gailbot_data]
root = "gailbot_data"
setting_src = "setting_source"
plugin_src = "plugin_source"
logfiles = "logfiles"

# contains relative paths for the files storing temporary data
[workspace.temporary]
root = "temporary"
transcribe_ws = "transcribe_ws"
format_ws = "format_ws"
analysis_ws = "analysis_ws"
data_copy = "data_copy"



