# contains relative paths for the output of gailbot
[output]
root = "result"
transcribe_result = "transcriptio"
analysis_result = "analysis"
format_result = "format"
media_file = "media"

[workspace]
root = "gailbot_workspace"

# contains relative paths for the directory storing the gailbot data
[workspace.gailbot_data]
root = "gailbot_workspace/gailbot_data"
setting_src = "gailbot_workspace/gailbot_data/setting_source"
plugin_src = "gailbot_workspace/gailbot_data/plugin_source"

# contains relative paths for the directory storing the logging files
[workspace.log]
root = "gailbot_workspace/logfiles"

# contains relative paths for the files storing temporary data
[workspace.temporary]
root = "gailbot_workspace/temporary"
transcribe_ws = "transcribe_ws"
format_ws = "format_ws"
analysis_ws = "analysis_ws"
data_copy = "data_copy"



