# contains the backedn data for running gailbot

[credential]
WATSON_API_KEY = "MSgOPTS9CvbADe49nEg4wm8_gxeRuf4FGUmlHS9QqAw3"
WATSON_LANG_CUSTOM_ID = "41e54a38-2175-45f4-ac6a-1c11e42a2d54"
WATSON_REGION = "dallas"
WATSON_BASE_LANG_MODEL = "en-US_NarrowbandModel"

[profileConfig]
SETTINGS_PROFILE_NAME = "default"
SETTINGS_PROFILE_EXTENSION = "json"

[directory]
WORKSPACE_DIRECTORY_PATH = "/Users/yike/Desktop/GB-UI/workdir" 
PLUGIN_DOWNLOADS = "/Users/yike/Desktop/GB-UI/plugin"

[plugin]
HIL_PLUGIN_URL = "https://sites.tufts.edu/hilab/files/2022/05/HiLabSuite.zip"

PLUGINS_TO_APPLY = [
        "constructTree",
        "utteranceDict",
        "speakerDict",
        "conversationDict",
        "convModelPlugin",
        "overlaps",
        "pauses",
        "gaps",
        "syllRate",
        "layerPrint01",
        "plainPrint",
        "chat",
        "txt",
        "csvPlugin",
        "csvWordLevel",
        "XMLtoCSV",
        "xmlSchema"
]

[threadControl]
maxThread = 1