workSpace = "/Users/yike/Documents/GitHub/GailBot/interface/gui/GailBot/workSpace"
plugin = "/Users/yike/Documents/GitHub/GailBot/interface/gui/GailBot/plugin"
frontend = "/Users/yike/Documents/GitHub/GailBot/interface/gui/Frontend"
