# contains all the predefined profile setting values
["HILAB default setting"]
plugin_setting = []

["HILAB default setting".RequiredSetting.Engine.whisper]
"language"       = "English"
"detect speaker" = false
