# contains all the predefined profile setting values
["HILAB default setting"]
plugin_setting = []

["HILAB default setting".engine_setting]
"engine"         = "whisper"
"language"       = "English"
"detect_speakers" = false
