# contains all the predefined profile setting values

["Air Force Study"]
Plugins = [ "constructTree",]

["Coffee Study"]
Plugins = [ "conversationDict", "utteranceDict", "constructTree",]

["HRI lab study"]
Plugins = [ "overlaps", "XMLtoCSV", "constructTree",]

["Air Force Study".PostTranscribe]
"Gap Length"                                         = "0"
"Turn End Threshold"                                 = "0"
"Large Pause - Lower Bound"                          = "0"
"Laughter Detection Module"                          = "OFF"
"Laughter Probability - Lower Bound"                 = "0"
"Laughter Length - Lower Bound"                      = "0"
"Upper Bound"                                        = "0"
"Lower Bound"                                        = "0"
"Beat Transcription Mode"                            = "OFF"
"FTO (Floor Transfer offset)Transcription Mode"      = "OFF"
"Syllable Rate mode"                                 = "OFF"

["Coffee Study".PostTranscribe]
"Gap Length"                                         = "0s"
"Turn End Threshold"                                 = "0s"
"Large Pause - Lower Bound"                          = "0s"
"Laughter Detection Module"                          = "ON"
"Laughter Probability - Lower Bound"                 = "0s"
"Laughter Length - Lower Bound"                      = "0s"
"Upper Bound"                                        = "0s"
"Lower Bound"                                        = "0s"
"Beat Transcription Mode"                            = "ON"
"FTO (Floor Transfer offset)Transcription Mode"      = "ON"
"Syllable Rate mode"                                 = "ON"

["HRI lab study".PostTranscribe]
"Gap Length"                                         = "0s"
"Turn End Threshold"                                 = "0s"
"Large Pause - Lower Bound"                          = "0s"
"Laughter Detection Module"                          = "OFF"
"Laughter Probability - Lower Bound"                 = "0s"
"Laughter Length - Lower Bound"                      = "0s"
"Upper Bound"                                        = "0s"
"Lower Bound"                                        = "0s"
"Beat Transcription Mode"                            = "OFF"
"FTO (Floor Transfer offset)Transcription Mode"      = "OFF"
"Syllable Rate mode"                                 = "OFF"

["Air Force Study".RequiredSetting."Output Form Data"]
language             = "Spanish"
"Number of speaker"  = "1"
gender0              = "Female"
gender1              = "Female"
gender2              = "Female"
"Output File Format" = "CHART"

["Coffee Study".RequiredSetting."Output Form Data"]
language             = "Spanish"
"Number of speaker"  = "1"
gender0              = "Female"
gender1              = "Female"
gender2              = "Female"
"Output File Format" = "CHART"

["HRI lab study".RequiredSetting."Output Form Data"]
language             = "Spanish"
"Number of speaker"  = "1"
gender0              = "Female"
gender1              = "Female"
gender2              = "Female"
"Output File Format" = "CHART"

["Air Force Study".RequiredSetting."Output Form Data"."Corpus Settings"]
"Corpus name"        = "enter corpus name"
"Corpus location"    = "enter corpus location"
"Corpus room layout" = "enter corpus room layout"
"Corpus situation"   = "enter situation"

["Coffee Study".RequiredSetting."Output Form Data"."Corpus Settings"]
"Corpus name"        = "enter corpus name"
"Corpus location"    = "enter corpus location"
"Corpus room layout" = "enter corpus room layout"
"Corpus situation"   = "enter situation"

["HRI lab study".RequiredSetting."Output Form Data"."Corpus Settings"]
"Corpus name"        = "enter corpus name"
"Corpus location"    = "enter corpus location"
"Corpus room layout" = "enter corpus room layout"
"Corpus situation"   = "enter situation"

["Air Force Study".RequiredSetting.Engine.CMU]
"language model"        = "English"
"custom language model" = "Air Force Study"
"acoustic model setting"           = "acoustic2"
"acoustic model setting(optional)" = "3"
"plugin"                           = "plugin 1"
"CMU setting option" = "setting option 1"
"username" = "HIL Lab"
"password" = "*********"

["Coffee Study".RequiredSetting.Engine.IBM]
"language model"        = "Spanish"
"custom language model" = "Air Force Study"
"acoustic model setting"           = "acoustic2"
"acoustic model setting(optional)" = "3"
"Advanced Setting Option 1" = "advanced 1"
"plugin"                    = "plugin 1"
"IBM setting option" = "setting option 2"
"username" = "HIL Lab"
"password" = "*********"

["HRI lab study".RequiredSetting.Engine.IBM]
"language model"        = "IBM language"
"custom language model" = "Air Force Study"
"acoustic model setting"           = "acoustic2"
"acoustic model setting(optional)" = "3"
"Advanced Setting Option 1" = "advanced 1"
"plugin"                    = "plugin 1"
"IBM setting option" = "setting option 3"
"username" = "HIL Lab"
"password" = "*********"