from .watsonInterface import load_watson_setting
from .googleInterface import load_google_setting
from .whisperInterface import load_whisper_setting
from .engineSettingInterface import EngineSettingInterface
from .pluginSettingsInterface import PluginSettingsInterface