# conatins the value for dimension data
[dimension]
WINMAXWIDTH         = 1400
WINMAXHEIGHT        = 1200
BTNWIDTH            = 165
BTNHEIGHT           = 40
SBTNWIDTH           = 100
SBTNHEIGHT          = 30
LBTNWIDTH           = 200
CONSOLEWIDTH        = 1000
CONSOLEHEIGHT       = 300
STATUSWIDTH         = 900
STATUSHEIGHT        = 30
INPUTWIDTH          = 250
INPUTHEIGHT         = 30
ICONBTN             = 50
SMALLICONBTN        = 30
TABLEWIDTH          = 1100
TABLEMINHEIGHT      = 350
TABLECONTAINERWIDTH = 1120
PROGRESSBARWIDTH    = 450
PROGRESSBARHEIGHT   = 40
LARGEDIALOGWIDTH    = 950
LARGEDIALOGHEIGHT   = 720
TOGGLEBARMAXWIDTH   = 600
TOGGLEBARMINWIDTH   = 500
TOGGLEVIEWOFFSET    = 20
STANDARDSPACING     = 10
SIDEBAR             = 200
FORMWIDTH           = 800
FORMMINHEIGHT       = 560
FORMMAXHEIGHT       = 700
DEFAULTTABHEIGHT    = 600
DEFAULTTABWIDTH     = 800
LOGO_WIDTH          = 120
LOGO_HEIGHT         = 40
SMALL_TABLE_WIDTH   = 450
SMALL_TABLE_HEIGHT  = 300
SMALL_SPACING       = 5
MEDIUM_SPACING      = 20
LARGE_SPACING       = 30
WIN_MIN_WIDTH       = 1140
WIN_MIN_HEIGHT      = 780
LARGE_ICON          = 80
OUTPUT_FORM_HEIGHT  = 350
COMBOBOX_HEIGHT     = 40 


[filetable.dimension]
fileUploadPage = [0.07,0.10,0.22,0.12,0.15,0.15,0.17]
confirmPage    = [0.11,0.34,0.34,0.2]
transcribePage = [0.22, 0.30, 0.47]
successPage    = [0.10, 0.30, 0.20, 0.20, 0.19]


