# conatins the value for dimension data
[dimension]
WINMAXWIDTH         = 1300
WINMAXHEIGHT        = 1200
BTNWIDTH            = 165
BTNHEIGHT           = 40
SBTNWIDTH           = 100
SBTNHEIGHT          = 30
LBTNWIDTH           = 200
CONSOLEWIDTH        = 1000
CONSOLEHEIGHT       = 300
STATUSWIDTH         = 900
STATUSHEIGHT        = 30
INPUTWIDTH          = 250
INPUTHEIGHT         = 30
ICONBTN             = 50
SMALLICONBTN        = 30
TABLEWIDTH          = 900
TABLEMINHEIGHT      = 300
TABLECONTAINERWIDTH = 920
PROGRESSBARWIDTH    = 450
PROGRESSBARHEIGHT   = 40
LARGEDIALOGWIDTH    = 950
LARGEDIALOGHEIGHT   = 720
TOGGLEBARMAXWIDTH   = 700
TOGGLEBARMINWIDTH   = 550
TOGGLEVIEWOFFSET    = 20
STANDARDSPACING     = 10
SIDEBAR             = 200
FORMWIDTH           = 650
FORMMINHEIGHT       = 550
FORMMAXHEIGHT       = 720
DEFAULTTABHEIGHT    = 450
DEFAULTTABWIDTH     = 600
LOGO_WIDTH          = 120
LOGO_HEIGHT         = 40
SMALL_TABLE_WIDTH   = 350
SMALL_TABLE_HEIGHT  = 300
SMALL_SPACING       = 5
MEDIUM_SPACING      = 20
LARGE_SPACING       = 30
WIN_MIN_WIDTH       = 1000
WIN_MIN_HEIGHT      = 780
LARGE_ICON          = 80
OUTPUT_FORM_HEIGHT  = 350
COMBOBOX_HEIGHT     = 40 


[filetable.dimension]
fileUploadPage = [0.07,0.06,0.17,0.12,0.15,0.15,0.08,0.20]
confirmPage    = [0.11,0.34,0.34,0.2]
transcribePage = [0.22, 0.30, 0.48]
successPage    = [0.10, 0.30, 0.20, 0.20, 0.2]


