# This file contains configurations required for Google Speech to text operations
# that the user should not be able to change.

# Defines default configuration settings
[google.defaults]
enable_automatic_punctuation    = true
enable_speaker_diarization      = false
enable_word_time_offsets        = true
language_code                   = "en-US"

# Contains configuration data about the Google Speech to Text engine
[google]
name = "Google Cloud Speech to Text Engine"
workspace  = "google_workspace"
maximum_size = 9000000
maximum_duration = 55


[google.key]
type = "service_account"
project_id = "gailbot-testing"
private_key_id = "2d9bf1d8326db0e71be0ed0dba15850d0653377e"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCTo7nYpK8aSFfk\nkmvcTB/aeKMUj1dzf684JuXAt0DytiptI1oRy24XzA6KK/nehN/LdRdnEQFM+LAk\nYryTqARjb+/ZM3l2GtaTtQdYWdYtiXzLoeDMFt64dzyv0zYPUnZp5HuXFiC0xPod\nWfv5TuoCKXamGze2lcbUcIIkKu68132i03OFRNr89KqGTX+MkcNUQ838upl7MFso\nKdldrU9TzT0U/H7TquUdIOFz0BveKMnS9/QkPvIH7pnHGYGl1eNIVoU7tP8kxDiK\niEq/VZ0bHWIM4Dew+MYTEYrO1z4NIVtW7euCzpScPI+ivkTFAE5m6RFt1X3IFzFd\n1Ej5oCrHAgMBAAECggEABS2QVo9MDt1rq7oQ61yGH3jsq0tts0DOqeb/Vtd2gSyv\nZz1+qrIaTd5bwi/RpyK84JteM0Cu7X6pWtVVrM4PPVePL2x1PZWqYerO86PO9bDl\nPhUS18WTkR+pcrczJa1sNsGLLhzaD8z6wq3FvxQr8+B1Z1T8CrzNCOVbQx54Wgod\nFeH+6vvQKFdU2Q/qtpP5VLRp8vufnY5QpdgLJYxwEUnvjxgANnGgLC24ehnSS+Iq\neyjBfoWIjQL0luNb/G9PyOH6QcoV8Ez69QF40429Oen+IdqPquWKuTFAxPb0O9BZ\nFejkjP/tm4CBNDTZMPBMnp+3qxDhhVj839yQNfOrOQKBgQDOn4K/Ly5N1aPkjuEK\nzHXWuiIbbPsiZbyqmfnKNF+CTUBYtqGVN9rdlux4V0mmHk+quKaqeAPsoLZg7jcU\n6ew6VFNO81pGDDc98CeO7fGAWnQIjUiwrw8YmsxUlJO+Uf3OwBEr0+j0mqiZ9tWJ\nvwKnPy5hvLDMSxngzUsuiI0XrwKBgQC2684/nZD+oSnFMt6WOEOVpwYrlYgLTnwT\ncMNM9x6CJ69E0VhfVxxryQr2BfArDF5JqxTLAZkSJp7J/SS1Q2zkr25JE1tBJ9GA\ns9XdgbGLOLOXVGlqOKGadDUthBTr2SVXqBKMWbIoLByKZFfzrqweVk2PXG+HawBM\nEhLsm77MaQKBgFyQuVJNIMFd5H6QQ+FCl8gKuxzuRdOzIEKNmIotzFvjn+AecWUY\nEMUUx/thn2z8R1SERKY5/ggUN6BVF/gWk+3NuUS1YMvgzR7CZ/ZwQrDt1O2/3cDJ\nrEmpj8CUj1vD/6CQCyFHXiW247GWEzQSjm2+sFi437umKYG8duHx6sOhAoGARtda\nAA8gyUxXJfUGeTz/B6Uw4Y4+qspRiSHhsRv/Z77AxTEiPYI6EpBAu3kfQzy+A1/L\nZLeQtZPZaTatkbm0IXjDiG+Dpt8p5uM+z1NcFCP4gYICdU3LYErjEWaWx6RILwN7\nc3mFYsN6piooWcprBDC+RugwlUxeSBez1oiWwwkCgYB1qs7Bvq0QKZch5K/9pCnp\ncSqmF+u4qfyTPVlozX7zQCM1uLzLz21+74VeBtIz0vB7IEQwkS2jjshx2Z0RccO9\nqd7GVVXX3FVPFKaWIZCh2TJanwjtfy0TwBs6MPIwEE9h1eAoHx17j6r5fEmasJj9\ntgsQ/UKgg0BQAR0FUXLVlw==\n-----END PRIVATE KEY-----\n"
client_email = "my-stt-sa@gailbot-testing.iam.gserviceaccount.com"
client_id = "107398407800627786209"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/my-stt-sa%40gailbot-testing.iam.gserviceaccount.com"

