

[whisper]
engine_name = "whisper"
model_name = "tiny"
[whisper.transcribe_configs]
remove_punctuation_from_words = true
compute_word_confidence = true
include_punctuation_in_confidence = false
refine_whisper_precision = false
min_word_duration = 0.04
plot_word_alignment = false
naive_approach = false
compression_ratio_threshold = 2.4
logprob_threshold = -1
no_speech_threshold = 0.6
condition_on_previous_text = true
verbose = true

# NOTE: Originally None but that is the default - uncomment for specific values
# This is because toml does not support NULL
# best_of = None
# beam_size = None
# patience = None
# length_penalty = None
# fp16 = None
