# contains all the predefined profile setting values

[Default]
Plugins = [ "constructTree",]

["Coffee Study"]
Plugins = [ "conversationDict", "utteranceDict", "constructTree",]

["HRI lab study"]
Plugins = [ "overlaps", "XMLtoCSV", "constructTree",]

[Default.PostTranscribe]
"Gap Length"                                         = "0"
"Turn End Threshold"                                 = "0"
"Large Pause - Lower Bound"                          = "0"
"Laughter Detection Module bool"                     = "OFF"
"Laughter Probability - Lower Bound"                 = "0"
"Laughter Length - Lower Bound"                      = "0"
"Upper Bound"                                        = "0"
"Lower Bound"                                        = "0"
"Beat Transcription Mode bool"                       = "OFF"
"FTO (Floor Transfer offset)Transcription Mode bool" = "OFF"
"Syllable Rate mode bool"                            = "OFF"

["Coffee Study".PostTranscribe]
"Gap Length"                                         = "0s"
"Turn End Threshold"                                 = "0s"
"Large Pause - Lower Bound"                          = "0s"
"Laughter Detection Module bool"                     = "ON"
"Laughter Probability - Lower Bound"                 = "0s"
"Laughter Length - Lower Bound"                      = "0s"
"Upper Bound"                                        = "0s"
"Lower Bound"                                        = "0s"
"Beat Transcription Mode bool"                       = "ON"
"FTO (Floor Transfer offset)Transcription Mode bool" = "ON"
"Syllable Rate mode bool"                            = "ON"

["HRI lab study".PostTranscribe]
"Gap Length"                                         = "0s"
"Turn End Threshold"                                 = "0s"
"Large Pause - Lower Bound"                          = "0s"
"Laughter Detection Module bool"                     = "OFF"
"Laughter Probability - Lower Bound"                 = "0s"
"Laughter Length - Lower Bound"                      = "0s"
"Upper Bound"                                        = "0s"
"Lower Bound"                                        = "0s"
"Beat Transcription Mode bool"                       = "OFF"
"FTO (Floor Transfer offset)Transcription Mode bool" = "OFF"
"Syllable Rate mode bool"                            = "OFF"

[Default.RequiredSetting."Output Form Data"]
language             = "Spanish"
"Number of speaker"  = "1"
gender0              = "Female"
gender1              = "Female"
gender2              = "Female"
"Output File Format" = "CHART"

["Coffee Study".RequiredSetting."Output Form Data"]
language             = "Spanish"
"Number of speaker"  = "1"
gender0              = "Female"
gender1              = "Female"
gender2              = "Female"
"Output File Format" = "CHART"

["HRI lab study".RequiredSetting."Output Form Data"]
language             = "Spanish"
"Number of speaker"  = "1"
gender0              = "Female"
gender1              = "Female"
gender2              = "Female"
"Output File Format" = "CHART"

[Default.RequiredSetting."Output Form Data"."Corpus Settings"]
"Corpus name"        = "enter corpus name"
"Corpus location"    = "enter corpus location"
"Corpus room layout" = "enter corpus room layout"
"Corpus situation"   = "enter situation"

["Coffee Study".RequiredSetting."Output Form Data"."Corpus Settings"]
"Corpus name"        = "enter corpus name"
"Corpus location"    = "enter corpus location"
"Corpus room layout" = "enter corpus room layout"
"Corpus situation"   = "enter situation"

["HRI lab study".RequiredSetting."Output Form Data"."Corpus Settings"]
"Corpus name"        = "enter corpus name"
"Corpus location"    = "enter corpus location"
"Corpus room layout" = "enter corpus room layout"
"Corpus situation"   = "enter situation"

[Default.RequiredSetting.Engine.CMU."1.language model setting"]
"1. language model"        = "English"
"2. custom language model" = "Air Force Study"

[Default.RequiredSetting.Engine.CMU."2.Acoustic Model Setting"]
"1. acoustic model setting"           = "acoustic2"
"2. acoustic model setting(optional)" = "3"
"3. plugin"                           = "plugin 1"

[Default.RequiredSetting.Engine.CMU."3.CMU specialised setting"]
"CMU setting option" = "setting option 1"

["Coffee Study".RequiredSetting.Engine.IBM."1.language model setting"]
"1. language model"        = "Spanish"
"2. custom language model" = "Air Force Study"

["Coffee Study".RequiredSetting.Engine.IBM."2.Acoustic Model Setting"]
"1. acoustic model setting"           = "acoustic2"
"2. acoustic model setting(optional)" = "3"

["Coffee Study".RequiredSetting.Engine.IBM."3.advanced setting"]
"1. Advanced Setting Option 1" = "advanced 1"
"2. plugin"                    = "plugin 1"

["Coffee Study".RequiredSetting.Engine.IBM."4.IBM specialised setting"]
"IBM setting option" = "setting option 2"

["HRI lab study".RequiredSetting.Engine.IBM."1.language model setting"]
"1. language model"        = "IBM language"
"2. custom language model" = "Air Force Study"

["HRI lab study".RequiredSetting.Engine.IBM."2.Acoustic Model Setting"]
"1. acoustic model setting"           = "acoustic2"
"2. acoustic model setting(optional)" = "3"

["HRI lab study".RequiredSetting.Engine.IBM."3.advanced setting"]
"1. Advanced Setting Option 1" = "advanced 1"
"2. plugin"                    = "plugin 1"

["HRI lab study".RequiredSetting.Engine.IBM."4.IBM specialised setting"]
"IBM setting option" = "setting option 3"
