title = "style toml"

[colors] 
GREEN = "#6E9B87"
ORANGE = "#EE6C4D"
BLUEWHITE = "#F0F6F9"
BLUELIGHT = "#D2E4EE"
BLUEMEDIUM = "#3D4A80"
BLUEDARK = "#293241"
GREYLIGHT = "#EBEBEB"
GREYMEDIUM1 = "#91969D"
GREYMEDIUM2 = "#767C85"
GREYDARK = "#545B67"
BORDERGREY = "#797979"
BLACK = "#000000"
WHITE = "#FFFFFF"
GREYEXTRALIGHT = "#F0F6F9"

[fontSizes]
BODY = "13px"
TEXT_FIELD = "12px"
SMALL="11px"
LINK = "15px"
HEADER1 = "32px" 
HEADER2  = "24px"
HEADER3  = "18px"
TABLE_ROW = "13px"
DESCRIPTION = "12px"
INSTRUCTION_CAPTION = "14px"
BTN = "14px" 

[dimensions]
WIN_MAXSIZE = QSize(1100, 900)
MARGIN_HORIZONTAL = "20px"
MARGIN_VERTICAL = "5px"
BGBUTTON = QSize(140, 40)
RBUTTON = QSize(130, 40)
MEDIUMBUTTON = QSize(100, 30)
ICONBUTTON = QSize(50, 50)
SMALLICONBUTTON = QSize(30,30)
INPUTFIELD = QSize(200, 30)
CONSOLE = QSize(1000, 300)
STATUSBAR = QSize(900, 30)
ACTION = QSize(100,35)
MEDIUMDIALOG = QSize(400,110)
LARGEDIALOG = QSize(400, 600)

[geometry]
CONSOLE = QRect(300, 700, 1000, 300)
MENUBAR = QRect(0, 0, 900, 37)