###### text values 
[text.links]
HILAB = "https://sites.tufts.edu/hilab"

[text.TranscribeSuccessText]
mainLabelText = "Transcription Successful"
transcribedFilesText = "Transcribed files and locations:"
moreBtnText = "Process more files"
returnBtnText = "Return to main menu"

[text.TranscribeProgressText]
mainLabelText = "Transcription in Progress"
loadingText = "Transcribing files..."
inProgressText = "Files in progress:"
cancelText = "Cancel"

[text.WelcomePageText]
audioInstructionText = "1. Select audio and video files \n or record live in Gailbot"
settingsInstructionText = "2. Apply settings"
transcribeInstructionText = "3. Transcribe"
fileInstructionText = "4. Get a transcribed file"
editInstructionText = "5. Edit settings \n or retranscribe"
welcomeText = "Welcome to GailBot"
captionText = "GailBot is the world's first application that lets you convert audio and\n video files into customizd transcripts."
startBtnText = "Get Started"
instructionText = "How GailBot Works"
resourcesText = "Resources"
tutorialText = "GailBot Beginner Tutorial"
guideText = "GailBot Settings Guide"
gbLinkText = "GailBot.com"
moreInfoText = "For more information visit"

[text.FileUploadPageText]
header = "Files to Transcribe"
returnMainText = "Return to Main Menu"
recordBtnText = "Record live"
uploadBtnText = "Add From Device"
transcribeBtnText = "Transcribe"
removeBtnText = "Remove All"
settingBtnText = "⚙"
dropText = "Drop File Here to Upload"
chooseLocalText = "Choose From Local"
chooseSetHeader = "select setting profile"
selectSetText = "select settings"
selectPlaceHolderText = "None"
selectFolderText = "Select Folder"
chooseOutPutText = "Choose Output Directory"
fileFilter = ["audio file (*.wav)","directory (/)"]
removeWarnText = "Remove all files?"

[text.RecordPageText]
basic = "Basic"
filename = "Filename"
mp3 = "MP3"
wav = "WAV"
format = "Audio Format"
advanced = "Advanced"
rate = "Recording Rate (Hertz)"
duration = "Max Recording Duration"
cancel = "Cancel"
start = "Start Recording"
test = "Test MicroPhone"
recSet = "Recording Settings"
record = "Record Audio File"
end = "End Recording"

[text.ProfilePageText]
cancelBtn = "Cancel"
saveBtn = "Save and Exit"
newProfileBtn = "Create New Profile"
reuquiredSetBtn = "Required Settings"
postSetBtn = "Post-Transcription Settings"
newPluginBtn = "Add New Plugin"
pluginSetBtn = "Plugin Setting"
postSetHeader = "Post-Transcription Settings"
postSetCaption = "These settings are applied after the file is created."
requiredSetHeader =  "Required Settings"
requiredSetCaption =  "These settings are required before transcription and cannot be edited after transcription."
pluginHeader = "Choose Plugins"
pluginCaption = "These plugins are applied to transcription process"

[text.SystemSettingPage]
header = "System Setting"
caption = "These settings are applied for system setting"
cancelBtn = "Cancel"
saveBtn = "Save and Exit"

[text.ConfirmTranscriptionPageText]
confirmLabel = "Confirm Files and Settings"
confirm = "Confirm"
cancel = "Cancel"

[text.RecordInProgressPageText]
start = "Start Recording"
cancel = "Cancel"
end = "End Recording"

#################   TODO: insert values #################
[text.CreateNewProfilePageText]  
confirmProfileNameBtn = "Start"
emptyNameMsg = "The profile name cannot be empty"
emptyUserMsg = "Please enter user name and password"
engineSettingHeader = "Speech to text settings"
outputSettingHeader =  "Output format settings"
cofirmBtn = "confirm"

[text.ChooseFileTabText]
WindowTitle = "Upload File"
TabTitle    = "Add New File"
TabHeader1  = "add file"
TabHeader2  = "choose setting"
TabHeader3  = "select output"

[text.WindowTitle]
consoleWindow = "Console Window"

[text.CreateNewProfileText]
WindowTitle = "Create New Profile"
TabTitle = "Create New Profile"
TabHeader1 = "Profile Name"
TabHeader2 = "Basic Settings"
TabHeader3 = "Optional Settings"
TabHeader4 = "Output File Format Setting"
TabHeader5 = "Post Transcribtion Settion"
TabHeader6 = "Plugin Setting"

[text.MainStackText]
ProfileSettingBtn = "Porfile Setting"
SystemSettingBtn  = "System Setting"

[text.OutputFormatForm]
header = "Output File Format"
CorpuFormHeader = "Corpus Settings"
LanguageHeader  = "language"
FileFormatHeader = "File Format"
SpeakerHeader = "Number of Speaker"
TextWrap = "Text-Wrapping"

[text.RequiredSettingForm]
engineSetHeader = "Speech to text settings"
outputSetHeader = "Output File Format Settings"