[THRESHOLD]
GAPS_LB = 0.3
OVERLAP_MARKERLIMIT = 4.0
LB_LATCH = 0.01
UB_LATCH = 0.09
LB_PAUSE = 0.2
UB_PAUSE = 1.0
LB_MICROPAUSE = 0.1
UB_MICROPAUSE = 0.2
LB_LARGE_PAUSE = 1.0
TURN_END_THRESHOLD_SECS = 0.1

[LABEL.DEFAULT]
SPEAKERLABEL  = "SP_"
GAPMARKER     = "(Gap)"
OVERLAPMARKER = "(Overlap)"
PAUSE         = "(Pause)"
OVERLAPMARKER_CURR_START = " < "
OVERLAPMARKER_CURR_END   = " > [<]"
OVERLAPMARKER_NEXT_START = " < "
OVERLAPMARKER_NEXT_END   = " > [>]"

[LABEL.CSV]
SPEAKERLABEL = "SP_"
GAPMARKER     = "(Gap)"
OVERLAPMARKER = "(Overlap)"
PAUSE         = "(Pause)"
OVERLAPMARKER_CURR_START = "Overlap First Start"
OVERLAPMARKER_CURR_END   = "Overlap First End"
OVERLAPMARKER_NEXT_START = "Overlap Second Start"
OVERLAPMARKER_NEXT_END   = "Overlap Second End"

[LABEL.CHAT]
SPEAKERLABEL  = "SP_"
GAPMARKER     = "(Gap)"
OVERLAPMARKER = "(Overlap)"
PAUSE         = "(Pause)"
OVERLAPMARKER_CURR_START = " < "
OVERLAPMARKER_CURR_END   = " > [<]"
OVERLAPMARKER_NEXT_START = " < "
OVERLAPMARKER_NEXT_END   = " > [>]"

[LABEL.TXT]
SPEAKERLABEL = "SP_"
GAPMARKER     = "(Gap)"
OVERLAPMARKER = "(Overlap)"
PAUSE         = "(Pause)"
OVERLAPMARKER_CURR_START = " < "
OVERLAPMARKER_CURR_END   = " > [<]"
OVERLAPMARKER_NEXT_START = " < "
OVERLAPMARKER_NEXT_END   = " > [>]"

[LABEL.XML]
SPEAKERLABEL = "SP"
GAPMARKER     = "(Gap)"
OVERLAPMARKER = "(Overlap)"
PAUSE         = "(Pause)"
OVERLAPMARKER_CURR_START = " < "
OVERLAPMARKER_CURR_END   = " > [<]"
OVERLAPMARKER_NEXT_START = " < "
OVERLAPMARKER_NEXT_END   = " > [>]"








