[fontSizes]
BODY                = "15px"
TEXT_FIELD          = "15px"
SMALL               = "11px"
LINK                = "15px"
HEADER1             = "40px"
HEADER2             = "28px"
HEADER3             = "24px"
HEADER4             = "18px"
DESCRIPTION         = "16px"
INSTRUCTION_CAPTION = "20px"
BTN                 = "15px"
SETTINGICON         = "40px"
TABLE_ROW           = 15



