[fontSizes]
BODY = "13px"
TEXT_FIELD = "12px"
SMALL = "11px"
LINK = "15px"
HEADER1 = "32px"
HEADER2 = "24px"
HEADER3 = "18px"
HEADER4 = "15px"
DESCRIPTION = "12px"
INSTRUCTION_CAPTION = "14px"
BTN = "14px"
SETTINGICON = "40px"
TABLE_ROW = 13
