[fontSizes]
BODY = "10px"
TEXT_FIELD = "8px"
SMALL = "8px"
LINK = "12px"
HEADER1 = "28px"
HEADER2 = "20px"
HEADER3 = "14px"
HEADER4 = "12px"
DESCRIPTION = "7px"
INSTRUCTION_CAPTION = "10px"
BTN = "10px"
SETTINGICON = "40px"
TABLE_ROW = 10
