[fontSizes]
BODY                = "10px"
TEXT_FIELD          = "8px"
SMALL               = "8px"
LINK                = "12px"
HEADER1             = "28px"
HEADER2             = "20px"
HEADER3             = "14px"
TABLE_ROW           = "10px"
DESCRIPTION         = "7px"
INSTRUCTION_CAPTION = "10px"
BTN                 = "10px"
SETTINGICON         = "40px"



